[build]
  command = "pip install -r requirements.txt && python app.py"
  publish = "static"  # or wherever your frontend build assets live

[build.environment]
  FLASK_APP = "app.py"
  FLASK_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
